namespace: madtransfer

image:
  tag: "v0.2.0"

clusterIssuer:
  enabled: true

certification:
  email: "oveldman@gmail.com"
  commonDomain: "www.mad-world.eu"
  country: "NL"

madtransfer:
  api:
    deployment: "mad-transfer-api-deployment"
    app: "mad-transfer-api"
    name: "mad-transfer-api"
    loadBalancer: "mad-transfer-api-load-balancer"
    image: "ghcr.io/madworldnl/mad-transfer-api"
    host: "transfer-api.mad-world.eu"
    
  web:
    deployment: "mad-transfer-web-deployment"
    app: "mad-transfer-web"
    name: "mad-transfer-web"
    loadBalancer: "mad-transfer-web-load-balancer"
    image: "ghcr.io/madworldnl/mad-transfer-web"
    host: "transfer.mad-world.eu"
    
database:
  enabled: true
  name: postgres
  dbName: MadTransfer
  username: app
  password: "nonExistingKey1234"
  size:
    single: 1Gi
    combined: 4Gi
  secret:
    name: postgres-secret
  storageclass: local-path