namespace: madtransfer

image:
  tag: "v0.6.0"

clusterIssuer:
  enabled: true

certification:
  email: "oveldman@gmail.com"
  commonDomain: "www.mad-world.eu"
  country: "NL"

madtransfer:
  api:
    deployment: "mad-transfer-api-deployment"
    app: "mad-transfer-api"
    name: "mad-transfer-api"
    loadBalancer: "mad-transfer-api-load-balancer"
    image: "ghcr.io/madworldnl/mad-transfer-api"
    host: "transfer-api.mad-world.eu"
    
  web:
    deployment: "mad-transfer-web-deployment"
    app: "mad-transfer-web"
    name: "mad-transfer-web"
    loadBalancer: "mad-transfer-web-load-balancer"
    image: "ghcr.io/madworldnl/mad-transfer-web"
    host: "transfer.mad-world.eu"
    
database:
  enabled: true
  name: postgres
  dbName: MadTransfer
  username: app
  password: "nonExistingKey1234"
  size:
    single: 1Gi
    combined: 4Gi
  secret:
    name: postgres-secret
  storageclass: local-path
  connection:
    readwrite: "postgres-rw"
    read: "postgres-r"
    
admin:
  database:
    enabled: true
    deployment: "pgadmin-deployment"
    loadBalancer: "pgadmin-balancer"
    app: "pgadmin"
    name: "pgadmin"
    username: "admin@mad-world.nl"
    password: "nonExistingKey1234"
    image: "dpage/pgadmin4"
    tag: "9"
    host: "database.mad-world.eu"
    secret:
      name: "pgadmin-secret"
    
storage:
  name: "objectstorage"
  host: "https://s3.de.io.cloud.ovh.net"
  accesskey: "nonExistingKey1234"
  secretkey: "nonExistingKey1234"
  bucket:
    name: "madtransfer-production"
  

keycloak:
  loadBalancer: "keycloak"
  host: "identity.mad-world.eu"