# docker compose --env-file docker-compose.env up --build --force-recreate
name: mad-transfer
services:
  api:
    image: ghcr.io/madworldnl/mad-transfer-api:${IMAGE_TAG}
    container_name: api
    build:
      context: .
      dockerfile: ./src/MadWorldNL.MadTransfer.Controllers.Api/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:8080"
      - "3001:8081"
    networks:
      - api
      - postgres
  web:
    image: ghcr.io/madworldnl/mad-transfer-web:${IMAGE_TAG}
    container_name: web
    build:
      context: .
      dockerfile: ./src/MadWorldNL.MadTransfer.Controllers.Web/Dockerfile
    ports:
      - "4201:8080"
    networks:
      - api
  database:
    image: postgres:17
    container_name: mad-transfer-database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MadPassword1234!
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  api:
  postgres: