# docker compose --env-file docker-compose.env up --build --force-recreate
name: mad-transfer
services:
  api:
    image: ghcr.io/madworldnl/mad-transfer-api:${IMAGE_TAG}
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./src/MadWorldNL.MadTransfer.Controllers.Api/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__Host=database
      - StorageSettings__Host=http://storage-server:9444
      - Authentication__Authority=http://host.docker.internal:5555/realms/madworld
      - Authentication__ValidateUser=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "3000:8080"
      - "3001:8081"
    networks:
      - api
      - postgres
  web:
    image: ghcr.io/madworldnl/mad-transfer-web:${IMAGE_TAG}
    container_name: web
    build:
      context: .
      dockerfile: ./src/MadWorldNL.MadTransfer.Controllers.Web/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3002:80"
      - "3003:443"
    networks:
      - api
  database:
    image: postgres:17
    container_name: mad-transfer-database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MadPassword1234!
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  database-admin:
    image: dpage/pgadmin4:9
    container_name: database-admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.nl
      - PGADMIN_DEFAULT_PASSWORD=Secret1234
    ports:
      - "9080:80"
      - "9081:443"
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  storage-server:
    image: scireum/s3-ninja:8.5.0
    container_name: storage-server
    ports:
      - "9444:9000"
    volumes:
      - storage-data:/home/sirius/data
  authentication-server:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "5555:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - 18888:18888
      - 18889:18889
      - 18890:18890
  log-server:
    image: datalust/seq:2025
    container_name: log-server
    profiles: [ open-telemetry ]
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "MadPassword1234!" # Dev Password: MadPassword4321!
    ports:
      - "5341:80"
    volumes:
      - log-data:/data
volumes:
  postgres-data:
  pgadmin-data:
  keycloak-data:
  storage-data:
  log-data:
networks:
  api:
  postgres: