apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.madtransfer.api.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.madtransfer.api.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.madtransfer.api.app }}
      task: {{ .Values.madtransfer.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.madtransfer.api.app }}
        task: {{ .Values.madtransfer.api.name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.madtransfer.api.name }}
          image: {{ .Values.madtransfer.api.image }}:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
              ephemeral-storage: "1Gi"
            limits:
              cpu: 100m
              memory: 500Mi
              ephemeral-storage: "1Gi"
          env:
            - name: Authentication__Authority
              value: https://{{ .Values.keycloak.host }}/realms/madworld
            - name: DatabaseSettings__Host
              value: {{ .Values.database.connection.readwrite }}
            - name: DatabaseSettings__Port
              value: "5432"
            - name: DatabaseSettings__DbName
              value: {{ .Values.database.dbName }}
            - name: DatabaseSettings__User
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: username
            - name: DatabaseSettings__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: password
            - name: Cors__Origins__[0]
              value: https://{{ .Values.madtransfer.web.host }}
            - name: Cors__Origins__[1]
              value: https://{{ .Values.certification.commonDomain }}
            - name: OpenTelemetrySettings__Mode
              value: FullStack
            - name: OpenTelemetrySettings__Seq__Url
              value: http://{{ .Values.logger.loadBalancer }}
            - name: OpenTelemetrySettings__Seq__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.logger.secret.name }}
                  key: apikeyapi
            - name: StorageSettings__Host
              value: {{ .Values.storage.host }}
            - name: StorageSettings__BucketName
              value: {{ .Values.storage.bucket.name }}
            - name: StorageSettings__AccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.name }}
                  key: accesskey
            - name: StorageSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.name }}
                  key: secretkey
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.madtransfer.api.loadBalancer }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.madtransfer.api.app }}
    task: {{ .Values.madtransfer.api.name }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  