apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    allow-snippet-annotations: "true"
    cert-manager.io/cluster-issuer: "lets-encrypt"
    cert-manager.io/common-name: {{ .Values.certification.commonDomain }}
    cert-manager.io/subject-countries: {{ .Values.certification.country }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "Referrer-Policy: same-origin";
      more_set_headers "Content-Security-Policy: default-src 'self' https://{{ .Values.certification.commonDomain }} https://{{ .Values.madtransfer.api.host }} https://{{ .Values.madtransfer.web.host }} https://{{ .Values.admin.database.host }} https://{{ .Values.keycloak.host }}";
      
spec:
  {{- if .Values.clusterIssuer.enabled }}
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.certification.commonDomain }}
        - {{ .Values.madtransfer.api.host }}
        - {{ .Values.madtransfer.web.host }}
        - {{ .Values.admin.database.host }}
        - {{ .Values.keycloak.host }}
      secretName: madworld-tls
  {{ end }}
  rules:
    - host: {{ .Values.madtransfer.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.madtransfer.api.loadBalancer }}
                port:
                  number: 8080
    - host: {{ .Values.madtransfer.web.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.madtransfer.web.loadBalancer }}
                port:
                  number: 80
    - host: {{ .Values.certification.commonDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.madtransfer.web.loadBalancer }}
                port:
                  number: 80
    - host: {{ .Values.keycloak.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.loadBalancer }}
                port:
                  number: 8080
    - host: {{ .Values.admin.database.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.admin.database.loadBalancer }}
                port:
                  number: 80