namespace: madtransfer-development

image:
  tag: "v0.8.0"

clusterIssuer:
  enabled: false

madtransfer:
  api:
    host: "transfer-api.mad-world.local"
  web:
    host: "transfer.mad-world.local"
    
admin:
  database: 
    host: "database.mad-world.local"

keycloak:
  host: "identity.mad-world.local"