namespace: madtransfer-development

image:
  tag: "v0.10.0"

clusterIssuer:
  enabled: false
  
certification:
  commonDomain: "www.mad-world.local"

madtransfer:
  api:
    host: "transfer-api.mad-world.local"
  web:
    host: "transfer.mad-world.local"
  
madtools:
  api:
    host: "tools-api.mad-world.local"
    
admin:
  database: 
    host: "database.mad-world.local"

keycloak:
  host: "identity.mad-world.local"
  
logger:
  host: "log.mad-world.local"