name: Build & Push Docker Compose Services

on:
  push:
    branches:
      - main

jobs:
  docker-compose-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM64 builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build services
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -f src/MadWorldNL.MadTransfer.Controllers.Api/Dockerfile --tag ghcr.io/madworldnl/mad-transfer-api:latest .
          docker buildx build --platform linux/amd64,linux/arm64 -f src/MadWorldNL.MadTransfer.Controllers.Web/Dockerfile --tag ghcr.io/madworldnl/mad-transfer-web:latest .

      - name: Push services for linux/amd64
        run: |
          docker push ghcr.io/madworldnl/mad-transfer-api
          docker push ghcr.io/madworldnl/mad-transfer-web