name: Build & Push Docker Compose Services Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-compose-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM64 builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push service api
        run: docker buildx build --platform linux/amd64,linux/arm64 -f src/MadWorldNL.MadTransfer.Controllers.Api/Dockerfile --tag ghcr.io/madworldnl/mad-transfer-api:$GITHUB_REF_NAME --push .

      - name: Build & push service web
        run: docker buildx build --platform linux/amd64,linux/arm64 -f src/MadWorldNL.MadTransfer.Controllers.Web/Dockerfile --tag ghcr.io/madworldnl/mad-transfer-web:$GITHUB_REF_NAME --push .