name: Build & Push Docker Compose Services Tag

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-compose-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM64 builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build services on linux/amd64
        run: docker compose -f docker-compose.yml --env-file docker-compose-tag.env build --build-arg BUILDPLATFORM=linux/amd64 api web

      - name: Push services for linux/amd64
        run: |
          docker push --platform linux/amd64 ghcr.io/madworldnl/mad-transfer-api
          docker push --platform linux/amd64 ghcr.io/madworldnl/mad-transfer-web

      - name: Build services on linux/arm64
        run: docker compose -f docker-compose.yml --env-file docker-compose-tag.env build --build-arg BUILDPLATFORM=linux/arm64 api web

      - name: Push services for linux/arm64
        run: |
          docker push --platform linux/arm64 ghcr.io/madworldnl/mad-transfer-api
          docker push --platform linux/arm64 ghcr.io/madworldnl/mad-transfer-web